"""Integration test: parser must handle real CLEVR scene_desc strings.

Unlike `test_scene_parser.py` (inline synthetic fixtures), this test runs the
parser against 30 real strings drawn from the SCITAS CLEVR val split. It
catches regex drift: if the on-disk format changes or the GPT-2 round-trip
introduces artefacts, this test fails loudly instead of evaluation silently
returning `scene_desc_*: nan` for every variant.

The fixture is generated by `nano4M/scripts/extract_scene_desc_samples.py`
(run on SCITAS). Until that file exists, this test skips with a helpful
message.

Run:
    cd nano4M && python -m pytest tests/test_scene_parser_integration.py -v
"""
from __future__ import annotations

from pathlib import Path

import pytest

from nanofm.evaluation.scene_parser import parse_scene_description


CLEVR_SHAPES = {"cube", "sphere", "cylinder"}
CLEVR_COLORS = {"gray", "grey", "red", "blue", "green", "brown", "purple", "cyan", "yellow"}
CLEVR_MATERIALS = {"metal", "rubber", "metallic", "rubbery"}

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "scene_desc_samples.txt"


def _load_fixture() -> list[tuple[int, str, str]]:
    """Return a list of (sample_idx, form, text) tuples.

    `form` is 'RAW' or 'ROUNDTRIP'. The file layout is produced by
    `scripts/extract_scene_desc_samples.py`.
    """
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"Fixture {FIXTURE_PATH} not found. "
            f"Run scripts/extract_scene_desc_samples.py on SCITAS first."
        )
    entries: list[tuple[int, str, str]] = []
    current_idx = -1
    for line in FIXTURE_PATH.read_text().splitlines():
        if line.startswith("# sample "):
            current_idx = int(line.split()[2])
        elif line.startswith("RAW "):
            entries.append((current_idx, "RAW", line.split("|", 1)[1].strip()))
        elif line.startswith("ROUNDTRIP"):
            entries.append((current_idx, "ROUNDTRIP", line.split("|", 1)[1].strip()))
    if not entries:
        pytest.skip(
            f"Fixture {FIXTURE_PATH} exists but no RAW/ROUNDTRIP entries were "
            f"parsed. The file layout may have drifted from the extractor."
        )
    return entries


@pytest.fixture(scope="module")
def fixture_entries() -> list[tuple[int, str, str]]:
    return _load_fixture()


def test_fixture_has_both_forms(fixture_entries):
    """Fixture must contain 30 samples, each with RAW and ROUNDTRIP."""
    indices = sorted({e[0] for e in fixture_entries})
    # Up to 30 — permissive to allow extracting fewer during debugging.
    assert len(indices) >= 5, f"need at least 5 samples, got {len(indices)}"
    for idx in indices:
        forms = {e[1] for e in fixture_entries if e[0] == idx}
        assert "RAW" in forms, f"sample {idx} missing RAW"
        assert "ROUNDTRIP" in forms, f"sample {idx} missing ROUNDTRIP"


def test_every_entry_parses_nonempty(fixture_entries):
    """Every real scene_desc string must parse to at least one SceneObject.

    This is the real Week-1 gate: catches the "regex looked right but didn't
    match actual CLEVR output" bug before training launches.
    """
    failures = []
    for idx, form, text in fixture_entries:
        objs = parse_scene_description(text)
        if len(objs) == 0:
            failures.append((idx, form, text[:200]))
    assert not failures, (
        f"{len(failures)} scene_desc strings parsed to []: "
        + "\n".join(f"  sample={i} form={f} text={t!r}" for i, f, t in failures[:5])
        + ("\n  …" if len(failures) > 5 else "")
    )


def test_parsed_fields_are_in_clevr_vocabulary(fixture_entries):
    """Every parsed object must use CLEVR shapes / colors / materials."""
    oddities = []
    for idx, form, text in fixture_entries:
        for obj in parse_scene_description(text):
            if obj.shape not in CLEVR_SHAPES:
                oddities.append((idx, form, "shape", obj.shape, text[:120]))
            if obj.color not in CLEVR_COLORS:
                oddities.append((idx, form, "color", obj.color, text[:120]))
            if obj.material not in CLEVR_MATERIALS:
                oddities.append((idx, form, "material", obj.material, text[:120]))
    assert not oddities, (
        f"{len(oddities)} parsed fields are outside the CLEVR vocabulary: "
        + "\n".join(
            f"  sample={i} form={f} field={fld} value={v!r}  ctx={c!r}"
            for i, f, fld, v, c in oddities[:5]
        )
    )


def test_raw_and_roundtrip_parse_equivalently(fixture_entries):
    """For each sample, the RAW caption and the GPT-2 round-tripped caption
    should parse to the same list of SceneObjects. If they don't, the GPT-2
    tokenizer is introducing drift the regex must tolerate."""
    by_idx: dict[int, dict[str, str]] = {}
    for idx, form, text in fixture_entries:
        by_idx.setdefault(idx, {})[form] = text

    mismatches = []
    for idx, forms in by_idx.items():
        raw_text = forms.get("RAW", "")
        rt_text = forms.get("ROUNDTRIP", "")
        raw_objs = parse_scene_description(raw_text)
        rt_objs = parse_scene_description(rt_text)
        if raw_objs != rt_objs:
            mismatches.append((idx, raw_objs, rt_objs))
    assert not mismatches, (
        f"{len(mismatches)} samples parse differently from RAW vs ROUNDTRIP. "
        f"Regex must tolerate whatever GPT-2 decode introduces. "
        f"First mismatches: {mismatches[:3]}"
    )
