"""Extract ground-truth CLEVR scene_desc strings for the parser test fixture.

Run on SCITAS (CLEVR data is mounted at /work/com-304/datasets/clevr_com_304/,
not available on the local laptop):

    cd nano4M && python scripts/extract_scene_desc_samples.py

Output: `nano4M/tests/fixtures/scene_desc_samples.txt` — 30 real scene_desc
strings from the val split, each emitted twice:

  1. RAW: the caption as it sits on disk in the dataset's .json file
     (augmentation index 0).
  2. ROUNDTRIP: GPT-2-tokenise → decode(skip_special_tokens=True). This is
     what the parser actually receives at evaluation time once the model
     generates tokens and we decode them.

The two must parse to equivalent SceneObject lists. If they differ, the
GPT-2 tokenizer is introducing drift that the parser must tolerate.

The file also prints a short summary (coord ranges, objects per scene) so
we can pick `position_threshold` in hungarian_match.py and
`position_tolerance_px` in metrics.py from real data rather than guessing.

The fixture file is ~a few KB, plain text, and safe to commit — these
captions are CLEVR-derived phrases with no PII.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import sys

# Allow running from repo root or from nano4M/
ROOT = Path(__file__).resolve().parent.parent  # nano4M/
sys.path.insert(0, str(ROOT))

from nanofm.data.multimodal.simple_multimodal_dataset import SimpleMultimodalDataset  # noqa: E402


DATA_ROOT = "/work/com-304/datasets/clevr_com_304/"
SPLIT = "val"
N_SAMPLES = 500
OUT_PATH = ROOT / "tests" / "fixtures" / "scene_desc_samples.txt"


def main() -> None:
    # Pin augmentation index 0 so RAW reads are deterministic.
    # sample_from_k_augmentations=1 forces __getitem__'s np.random.randint(0, 1) -> 0.
    dataset = SimpleMultimodalDataset(
        root_dir=DATA_ROOT,
        split=SPLIT,
        modalities=["scene_desc"],
        text_tokenizer_path="gpt2",
        text_max_length=256,
        sample_from_k_augmentations=1,
        transforms=None,
    )
    print(f"[info] loaded val split with {len(dataset)} samples")

    tokenizer = dataset.text_tokenizer

    lines: list[str] = []
    raw_captions: list[str] = []
    rt_captions: list[str] = []

    for i in range(min(N_SAMPLES, len(dataset))):
        file_name = dataset.file_names[i]
        json_path = Path(DATA_ROOT) / SPLIT / "scene_desc" / f"{file_name}.json"
        with open(json_path, "r") as f:
            captions = json.load(f)
        raw = captions[0]  # augmentation index 0 to match the dataset loader below

        sample = dataset[i]  # {'scene_desc': LongTensor[256]}
        token_ids = sample["scene_desc"].tolist()
        rt = tokenizer.decode(token_ids, skip_special_tokens=True)

        raw_captions.append(raw)
        rt_captions.append(rt)

        lines.append(f"# sample {i:02d}  file={file_name}")
        lines.append(f"RAW      | {raw}")
        lines.append(f"ROUNDTRIP| {rt}")
        lines.append("")

        if N_SAMPLES <= 30 or i < 5 or i >= N_SAMPLES - 3 or i % 50 == 0:
            print(f"[sample {i:03d}] RAW={raw[:100]}{'…' if len(raw) > 100 else ''}")

    # Write fixture file
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by nano4M/scripts/extract_scene_desc_samples.py\n"
        f"# source: {DATA_ROOT}{SPLIT}/scene_desc/*.json  augmentation_idx=0\n"
        f"# n_samples: {N_SAMPLES}  tokenizer: gpt2  max_length: 256\n"
        f"# Each sample has two lines:\n"
        f"#   RAW       — caption as stored on disk\n"
        f"#   ROUNDTRIP — GPT-2 decode(encode(RAW), skip_special_tokens=True)\n"
        f"# Parser must parse both to equivalent SceneObject lists.\n"
        f"\n"
    )
    OUT_PATH.write_text(header + "\n".join(lines) + "\n")
    print(f"\n[info] wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")

    # Summary stats — useful for picking thresholds in Step 5.
    n_roundtrip_drift = sum(1 for r, t in zip(raw_captions, rt_captions) if r.strip() != t.strip())
    print(f"\n[summary]")
    print(f"  samples                : {N_SAMPLES}")
    print(f"  roundtrip drift (RAW != ROUNDTRIP after .strip()): {n_roundtrip_drift}")
    if n_roundtrip_drift:
        print(f"    -> inspect fixture file; regex must tolerate GPT-2 drift")

    # Rough coord-range probe using a permissive fallback regex — only to eyeball
    # the coordinate space. The real parser regex is designed from this fixture.
    import re

    probe = re.compile(
        r"(?:x\s*=\s*(-?\d+)\s+y\s*=\s*(-?\d+))|(?:\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\))",
        re.IGNORECASE,
    )
    xs, ys = [], []
    n_objs_per_sample = []
    for s in raw_captions:
        matches = probe.findall(s)
        n_objs_per_sample.append(len(matches))
        for m in matches:
            x = m[0] or m[2]
            y = m[1] or m[3]
            if x and y:
                xs.append(int(x))
                ys.append(int(y))

    if xs:
        print(f"  x range                : [{min(xs)}, {max(xs)}]")
        print(f"  y range                : [{min(ys)}, {max(ys)}]")
    else:
        print(
            "  COORD PROBE FAILED — the permissive regex matched zero coords.\n"
            "  The on-disk format is different from both the study-guide and\n"
            "  Notebook-4-line-188 examples. Inspect the fixture before proceeding."
        )
    if n_objs_per_sample:
        print(
            f"  objects per scene      : "
            f"min={min(n_objs_per_sample)} max={max(n_objs_per_sample)} "
            f"mean={sum(n_objs_per_sample)/len(n_objs_per_sample):.1f}"
        )


if __name__ == "__main__":
    main()
